config/routes.rb
Rails.application.routes.draw do
  # Root path
  root 'sessions#new'
  
  # Session routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # User routes
  resources :users, only: [:new, :create, :edit, :update, :index, :destroy] 

  # Report routes
  resources :reports, only: [:new] do
    collection do
      get 'results', to: 'reports#show'
      get 'export', defaults: { format: 'xlsx' }
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/report.rb
class Report < ApplicationRecord
  self.abstract_class = true
  establish_connection :sendit
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    # Validates that the email is unique
    validates :email, uniqueness: { case_sensitive: false, message: 'wurde bereits angenommen' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :admin?
  before_action :check_session_timeout

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end
  
  def admin?
    current_user&.email == ENV['ADMIN_EMAIL']
  end
  
  # Ensures a user is logged in
  def require_login
    unless current_user
      flash[:alert] = "You must be logged in to access this page"
      redirect_to login_path
    end
  end

  # Specific checks for different roles could be defined here
  def ensure_admin
    unless admin?
      flash[:alert] = "Only the administrator has access to this area"
      redirect_to root_path # or wherever appropriate
    end
  end

  def check_session_timeout
    if current_user && session[:expires_at] && Time.current > session[:expires_at]
      reset_session
      flash[:alert] = "Your session has expired. Please sign in again"
      redirect_to root_path 
    else
      session[:expires_at] = 30.minutes.from_now
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :fetch_data, only: [:show, :export]

  def show
    if !@data_present
      render :new and return
    end
  end

  def export
    if !@data_present
      redirect_to new_report_path, alert: 'Startdatum und Enddatum sind erforderlich!' and return
    end
  
    respond_to do |format|
      format.xlsx {
        today = Date.today.strftime('%d%m%Y')
        filename = "Export_#{today}.xlsx"
        response.headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      }
    end
  end
  
  
  private

  def fetch_data
    start_date = params[:start_date]
    end_date = params[:end_date]

    if start_date.blank? || end_date.blank?
      @results = []
      flash[:alert] = 'Startdatum und Enddatum sind erforderlich!'
      return
      else
      @data_present = true
      formatted_start_date = DateTime.parse(start_date).strftime('%Y%m%d')
      formatted_end_date = DateTime.parse(end_date).strftime('%Y%m%d')

      sql_query = <<-SQL
        SELECT DISTINCT
          [ShippingDate],
          [CustomerAccountNr],
          [CustomerOrderNr],
          [OrderNr],
          [InvoiceNr],
          [DeliveryNoteNr]
        FROM
          SendIT.Printed
        WHERE
          Shipper = 'Dachser' AND
          CONVERT(INT, REPLACE(CONVERT(VARCHAR, ShippingDate, 102), '.', '')) BETWEEN ? AND ?
        ORDER BY
          ShippingDate ASC
      SQL

      all_results = Report.connection.exec_query(ActiveRecord::Base.sanitize_sql_array([sql_query, formatted_start_date, formatted_end_date]))
      @results = Kaminari.paginate_array(all_results.to_a).page(params[:page]).per(50)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id  
      redirect_to new_report_path
    else
      flash.now[:alert] = 'Ungültige E-Mail/Passwort'
      render 'new', status: :unprocessable_entity
    end
  end
  

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "Erfolgreich ausgeloggt"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :ensure_admin, only: [:new, :create, :destroy, :index]
  before_action :set_user, only: [:edit ,:update]
  before_action :correct_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
    Rails.logger.debug "Received params: #{params.inspect}"
    @user = User.new(user_params)
    if @user.save
      redirect_to new_report_path, notice: 'User registered successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update  
    #Verify current password for any update
    unless @user.authenticate(params[:user][:current_password])
      flash[:alert] = 'Wrong password'
      return render :edit, status: :unprocessable_entity
    end
         
    # Handle password change
    if params[:user][:password].present?
      # Ensure password confirmation matches new password
      unless params[:user][:password] == params[:user][:password_confirmation]
        flash.now[:alert] = 'Password confirmation does not match.'
        return render :edit, status: :unprocessable_entity
      end

      if @user.update(user_params)
        # Password change was successful, log out the user
        reset_session # Clear the session
        redirect_to login_path, notice: 'Your password has been changed. Please log in again with your new password.'
        return
      else
        # Handle the case where password update fails due to other validation issues
        render :edit, status: :unprocessable_entity
        return
      end
    end

    # Handle general updates (excluding password changes)
    if @user.update(user_params.except(:password, :password_confirmation))
      redirect_to new_report_path, notice: 'User updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end
  
  private

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless current_user == @user || current_user.admin?
      flash[:alert] = "Du bist nicht berechtigt, diese Aktion auszuführen."
      redirect_to(root_url)
    end
  end

  def user_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FetchIT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |key, message| %>
      <div class="container mt-3">
        <div class="alert <%= 'alert-success' if key == 'notice' %> <%= 'alert-danger' if key == 'alert' %>">
          <%= message %>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/reports/new.html.erb
<%= render 'users/header' %>

<body>
    <%= form_with url: results_reports_path, method: :get, local: true do |form| %>
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group">
                                <%= form.label :start_date, 'Start Date' %>
                                <%= form.date_field :start_date, required: true, class: 'form-control' %>
                            </div>
                            <div class="form-group">
                                <%= form.label :end_date, 'End Date' %>
                                <%= form.date_field :end_date, required: true, class: 'form-control' %>
                            </div>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <%= form.submit "Generate Report", class: "btn btn-primary mt-3" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</body>

app/views/reports/show.html.erb
<%= render 'users/header' %>

<div class="table-responsive custom-table-container mt-5" style="max-width: 80%; margin: auto;">
  <table class="table table-striped table-bordered">
    <% if @results.blank? %>
      <p>No records found.</p>
    <% else %>
    <thead>
      <tr>
        <th>Shipping Date</th>
        <th>Customer Account Nr</th>
        <th>Customer Order Nr</th>
        <th>Order Nr</th>
        <th>Invoice Nr</th>
        <th>Delivery Note Nr</th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result['ShippingDate'].strftime('%d-%m-%Y') %></td>
          <td><%= result['CustomerAccountNr'] %></td>
          <td><%= result['CustomerOrderNr'] %></td>
          <td><%= result['OrderNr'] %></td>
          <td><%= result['InvoiceNr'] %></td>
          <td><%= result['DeliveryNoteNr'] %></td>
        </tr>
      <% end %>
    </tbody>
    <% end %>
  </table>


    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <% if @results.blank? == false %>
        <%= link_to 'Excel exportieren', export_reports_path(format: :xlsx, start_date: params[:start_date], end_date: params[:end_date]),  class: 'btn btn-primary'%>
      <% end %>
    </div>


  <% if @results.present? %>
    <div class="d-flex justify-content-center" style="margin-top: 20px;">
      <%= paginate @results %>
    </div>
  <% end %>
</div>

app/views/users/_header.html.erb
<head class="p-3 m-0 border-0 bd-example m-0 border-0">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <%= link_to image_tag('Download.png', alt: 'FetchIT', width: '100', height: '70'), new_report_path %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="<%= request.original_url %>"><%= Date.today.strftime('%d-%m-%Y') %></a>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'Report', new_report_path, class: "nav-link"%>
                    </li>

                    <% if admin? %>
                        <li class="nav-item">
                            <%= link_to 'Registration', new_user_path, class: "nav-link" %>
                        </li>

                        <li class="nav-item">
                            <%= link_to 'Infos', users_path, class: "nav-link" %>
                        </li>
                    <% end %>

                    <li class="nav-item">
                        <%= link_to 'My Data', edit_user_path(current_user), class: "nav-link" %>
                    </li>
                   
                    <li class="nav-item">
                        <%= form_with url: logout_path, method: :delete, local: true do |form| %>
                        <%= form.submit "Logout", class: "nav-link btn btn-link" %>
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</head>

app/views/users/edit.html.erb
<%= render 'header' %>

<div class="table-responsive custom-table-container mt-5" style="max-width: 80%; margin: auto;">
    <%= form_with(model: @user, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
    <div class="form-group mb-3">
        <%= form.label :firstName, "First name", class: 'input-group-text' %>
        <%= form.text_field :firstName, id: :user_firstName, class: 'form-control', 'aria-label': "First name", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :lastName, "Last name", class: 'input-group-text' %>
        <%= form.text_field :lastName, id: :user_lastName, class: 'form-control', 'aria-label': "Last name", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :email, "Email", class: 'input-group-text' %>
        <%= form.email_field :email, id: :user_email, class: 'form-control', 'aria-label': "Email", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :current_password, "Current Password", class: 'input-group-text' %>
        <%= form.password_field :current_password, id: :user_current_password, class: 'form-control', 'aria-label': "Current Password", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>

    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-warning d-flex align-items-center alert-sm" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="16" height="16" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
        Leave password and password confirmation blank if you do not want to change the password!!!
        </div>
    </div>

    <div class="form-group mb-3">
        <%= form.label :password, "Password", class: 'input-group-text' %>
        <%= form.password_field :password, id: :user_password, class: 'form-control', 'aria-label': "Password", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :password_confirmation, "Confirm password", class: 'input-group-text' %>
        <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control', 'aria-label': "Confirm password", 'aria-describedby': "inputGroup-sizing-lg" %>
    </div>
    
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= form.submit "Update", class: "btn btn-success" %>
    </div>

    <% end %>
</div>

app/views/users/index.html.erb
<%= render 'header' %>
<div class="table-responsive custom-table-container mt-5" style="max-width: 80%; margin: auto;">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.firstName %></td>
          <td><%= user.lastName %></td>
          <td><%= user.email %></td>
          <td>
            <%= form_with url: user_path(user), method: :delete do %>
                <% if user.email != ENV['ADMIN_EMAIL']%>
                  <%= submit_tag 'Delete', data: { confirm: 'are you sure?' }, class: 'btn btn-danger' %>
                <% end%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'header' %>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <!-- Error Messages -->
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@user.errors.count, "Fehler") %> prevented registration:</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="registration-form-wrapper p-4 border rounded shadow">
        <h2 class="text-center mb-4">Registration</h2>
        <%= form_with(model: @user, local: true) do |form| %>
          <div class="form-group">
            <%= form.label :firstName, "First name", class: "form-label" %>
            <%= form.text_field :firstName, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :lastName, "Last name", class: "form-label" %>
            <%= form.text_field :lastName, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :email, "E-Mail", class: "form-label" %>
            <%= form.email_field :email, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :password, "Password", class: "form-label" %>
            <%= form.password_field :password, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :password_confirmation, "Confirm Password", class: "form-label" %>
            <%= form.password_field :password_confirmation, class: "form-control", required: true %>
          </div>

          <div class="text-center">
            <%= form.submit "Ok", class: "btn btn-primary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>